name = "jumptrainingai-ingestion-worker"
main = "src/index.js"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

# R2 bucket binding for video data storage
[[r2_buckets]]
binding = "VIDEO_BUCKET"
bucket_name = "jumptrainingai-videos"

# Environment variables (secrets will be added via wrangler secret put)
[vars]
ENVIRONMENT = "development"

# Routes for custom domain (optional - will use *.workers.dev by default)
# routes = [
#   { pattern = "jumptrainingai.example.com/*", zone_name = "example.com" }
# ]
